target:
	gcc -Wall -g -o ex01 ex01.c -lm -lpthread
	gcc -Wall -g -o ex03 ex03.c -lm -lpthread
	gcc -Wall -g -o ex05 ex05.c -lm -lpthread
	gcc -Wall -g -o ex06 ex06.c -lm -lpthread
	gcc -Wall -g -o ex07 ex07.c -lm -lpthread
	gcc -Wall -g -o ex08 ex08.c -lm -lpthread
	gcc -Wall -g -o ex11 ex11.c -lm -lpthread
	gcc -Wall -g -o ex12 ex12.c -lm -lpthread
	gcc -Wall -g -o ex13 ex13.c -lm -lpthread

clean:
	rm -rf ex01
	rm -rf ex03
	rm -rf ex05
	rm -rf ex06
	rm -rf ex07
	rm -rf ex08
	rm -rf ex11
	rm -rf ex12
	rm -rf ex13
	rm -rf *~
	rm -rf *.*~
