target:
	gcc -Wall -g -o exC exC.c -lm -lpthread
	g++ -Wall -g -o exCpp exCpp.cpp -lm -lpthread
	g++ -Wall -g -o exCandCpp exCandCpp.cpp -lm -lpthread

clean:
	rm -rf exC
	rm -rf exCpp
	rm -rf exCandCpp
	rm -rf *~
	rm -rf *.*~
