target:
	g++ -Wall -g -o set1 set1.cpp
	g++ -Wall -g -o set2 set2.cpp
	g++ -Wall -g -o student_sort student_sort.cpp

clean:
	/bin/rm -rf set1
	/bin/rm -rf set2
	/bin/rm -rf student_sort
	/bin/rm -rf *~
